# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            RoBo
tagline:          Robust Bayesian Optimization
description:      RoBO is a flexible framework for robust Bayesian Optimization.
url:              http://numairmansur.github.io
baseurl:          /RoboDocumentation1/

author:
  name:           'Numair Mansur'
  url:            https://numairmansur.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/automl/RoBO
